// This file is auto-generated by packages/hardhat/scripts/generateTsAbis.ts
// Do not edit manually. Run `yarn hardhat:deploy` to regenerate.
// This is a placeholder — deploy contracts first to populate this file.

const deployedContracts = {} as const;

export default deployedContracts;
export type DeployedContracts = typeof deployedContracts;
