import { HardhatRuntimeEnvironment } from "hardhat/types";
import * as fs from "fs";
import * as path from "path";

/**
 * generateTsAbis
 *
 * Reads hardhat-deploy deployment artifacts and generates a TypeScript file
 * at packages/nextjs/contracts/deployedContracts.ts containing the ABI and
 * address for each deployed contract, keyed by network name.
 *
 * This file is imported by the Next.js frontend for typed contract interactions.
 * It is regenerated on every `hardhat deploy` run.
 *
 * Called automatically by the extended `deploy` task in hardhat.config.ts.
 */
export default async function generateTsAbis(
  hre: HardhatRuntimeEnvironment
): Promise<void> {
  const deploymentsDir = path.join(__dirname, "..", "deployments");
  const outputPath = path.join(
    __dirname,
    "..",
    "..",
    "nextjs",
    "contracts",
    "deployedContracts.ts"
  );

  if (!fs.existsSync(deploymentsDir)) {
    console.log("generateTsAbis: no deployments directory found, skipping.");
    return;
  }

  const contractsByNetwork: Record<
    string,
    Record<string, { address: string; abi: unknown[] }>
  > = {};

  const networks = fs
    .readdirSync(deploymentsDir)
    .filter((f) => fs.statSync(path.join(deploymentsDir, f)).isDirectory());

  for (const network of networks) {
    const networkDir = path.join(deploymentsDir, network);
    const contractFiles = fs
      .readdirSync(networkDir)
      .filter((f) => f.endsWith(".json") && !f.startsWith("."));

    contractsByNetwork[network] = {};

    for (const contractFile of contractFiles) {
      const contractName = contractFile.replace(".json", "");
      const artifact = JSON.parse(
        fs.readFileSync(path.join(networkDir, contractFile), "utf8")
      ) as { address: string; abi: unknown[] };

      contractsByNetwork[network][contractName] = {
        address: artifact.address,
        abi: artifact.abi,
      };
    }
  }

  const output = `// This file is auto-generated by packages/hardhat/scripts/generateTsAbis.ts
// Do not edit manually. Run \`yarn hardhat:deploy\` to regenerate.
// Generated at: ${new Date().toISOString()}

const deployedContracts = ${JSON.stringify(contractsByNetwork, null, 2)} as const;

export default deployedContracts;
export type DeployedContracts = typeof deployedContracts;
`;

  // Ensure the output directory exists
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, output, "utf8");
  console.log(`generateTsAbis: wrote ${outputPath}`);
}
